config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :friends
  resources :unicorns
  # STEP 1: A ROUTE triggers a controller action
  # verb "/urls" => "namespace/controllers#action"
end

app/models/api.rb
module Api
  def self.table_name_prefix
    'api_'
  end
end

app/models/api/hello.rb
class Api::Hello < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :unicorn
end

app/models/unicorn.rb
class Unicorn < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/hellos_controller.rb
class Api::HellosController < ApplicationController
  before_action :set_api_hello, only: [:show, :edit, :update, :destroy]

  # GET /api/hellos
  # GET /api/hellos.json
  def index
    @api_hellos = Api::Hello.all
  end

  # GET /api/hellos/1
  # GET /api/hellos/1.json
  def show
  end

  # GET /api/hellos/new
  def new
    @api_hello = Api::Hello.new
  end

  # GET /api/hellos/1/edit
  def edit
  end

  # POST /api/hellos
  # POST /api/hellos.json
  def create
    @api_hello = Api::Hello.new(api_hello_params)

    respond_to do |format|
      if @api_hello.save
        format.html { redirect_to @api_hello, notice: 'Hello was successfully created.' }
        format.json { render :show, status: :created, location: @api_hello }
      else
        format.html { render :new }
        format.json { render json: @api_hello.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api/hellos/1
  # PATCH/PUT /api/hellos/1.json
  def update
    respond_to do |format|
      if @api_hello.update(api_hello_params)
        format.html { redirect_to @api_hello, notice: 'Hello was successfully updated.' }
        format.json { render :show, status: :ok, location: @api_hello }
      else
        format.html { render :edit }
        format.json { render json: @api_hello.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api/hellos/1
  # DELETE /api/hellos/1.json
  def destroy
    @api_hello.destroy
    respond_to do |format|
      format.html { redirect_to api_hellos_url, notice: 'Hello was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api_hello
      @api_hello = Api::Hello.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def api_hello_params
      params.require(:api_hello).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:name, :age, :unicorn_id)
    end
end

app/controllers/unicorns_controller.rb
class UnicornsController < ApplicationController
  before_action :set_unicorn, only: [:show, :edit, :update, :destroy]

  # GET /unicorns
  # GET /unicorns.json
  def index
    @unicorns = Unicorn.all
    # binding.pry
  end

  # GET /unicorns/1
  # GET /unicorns/1.json

  def show
  end

  # GET /unicorns/new
  def new
    @unicorn = Unicorn.new
  end

  # GET /unicorns/1/edit
  def edit
  end

  # POST /unicorns
  # POST /unicorns.json
  def create
    @unicorn = Unicorn.new(unicorn_params)

    respond_to do |format|
      if @unicorn.save
        format.html { redirect_to @unicorn, notice: 'Unicorn was successfully created.' }
        format.json { render :show, status: :created, location: @unicorn }
      else
        format.html { render :new }
        format.json { render json: @unicorn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unicorns/1
  # PATCH/PUT /unicorns/1.json
  def update
    respond_to do |format|
      if @unicorn.update(unicorn_params)
        format.html { redirect_to @unicorn, notice: 'Unicorn was successfully updated.' }
        format.json { render :show, status: :ok, location: @unicorn }
      else
        format.html { render :edit }
        format.json { render json: @unicorn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unicorns/1
  # DELETE /unicorns/1.json
  def destroy
    @unicorn.destroy
    respond_to do |format|
      format.html { redirect_to unicorns_url, notice: 'Unicorn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unicorn
      @unicorn = Unicorn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unicorn_params
      params.require(:unicorn).permit(:age, :color, :superpower, :theme_song)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :unicorn_id %>
    <%= form.text_field :unicorn_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friends</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Unicorn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.name %></td>
        <td><%= friend.age %></td>
        <td><%= friend.unicorn %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @friend.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @friend.age %>
</p>

<p>
  <strong>Unicorn:</strong>
  <%= @friend.unicorn %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnicornApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/unicorns/_form.html.erb
<%= form_with(model: unicorn, local: true) do |form| %>
  <% if unicorn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unicorn.errors.count, "error") %> prohibited this unicorn from being saved:</h2>

      <ul>
      <% unicorn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :superpower %>
    <%= form.text_field :superpower %>
  </div>

  <div class="field">
    <%= form.label :theme_song %>
    <%= form.text_field :theme_song %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/unicorns/edit.html.erb
<h1>Editing Unicorn</h1>

<%= render 'form', unicorn: @unicorn %>

<%= link_to 'Show', @unicorn %> |
<%= link_to 'Back', unicorns_path %>

app/views/unicorns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Unicorns</h1>

<table>
  <thead>
    <tr>
      <th>Age</th>
      <th>Color</th>
      <th>Superpower</th>
      <th>Theme song</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unicorns.each do |unicorn| %>
      <tr>
        <td><%= unicorn.age %></td>
        <td><%= unicorn.color %></td>
        <td><%= unicorn.superpower %></td>
        <td><%= unicorn.theme_song %></td>
        <td><%= link_to 'Show', unicorn %></td>
        <td><%= link_to 'Edit', edit_unicorn_path(unicorn) %></td>
        <td><%= link_to 'Destroy', unicorn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unicorn', new_unicorn_path %>

app/views/unicorns/new.html.erb
<h1>New Unicorn</h1>

<%= render 'form', unicorn: @unicorn %>

<%= link_to 'Back', unicorns_path %>

app/views/unicorns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Age:</strong>
  <%= @unicorn.age %>
</p>

<p>
  <strong>Color:</strong>
  <%= @unicorn.color %>
</p>

<p>
  <strong>Superpower:</strong>
  <%= @unicorn.superpower %>
</p>

<p>
  <strong>Theme song:</strong>
  <%= @unicorn.theme_song %>
</p>

<%= link_to 'Edit', edit_unicorn_path(@unicorn) %> |
<%= link_to 'Back', unicorns_path %>